# 
name: Develop Pull Requests Workflow
on: 
  pull_request:
    branches: develop

# Run Tests
jobs:
  build-and-test:
    # Run lastest ubuntu-latest OS
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js 16.2.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.2.0
          cache: 'npm'
      - name: Install Packages
        run: npm install
      
      - nane: Set Enviroment
        env:
          PORT: 8080
          BCRYPT_COST: ${{ develop.BCRYPT_COST }}
          DB_HOST: ${{ develop.DB_HOST }}
          DB_PORT: ${{ develop.DB_HOST }}
          DB_NAME: ${{ develop.DB_HOST }}
          TOKEN_EXPIRES_NUMBER: ${{ develop.DB_HOST }}
          TOKEN_EXPIRES_UNIT: ${{ develop.DB_HOST }}
          JWT_SECRET: ${{ develop.DB_HOST }}
          TOKEN_EXPIRATION_DAYS: ${{ develop.DB_HOST }}

      # Step 3: Set up docker container for database
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      # Step 4: run tests
      - name: Run Tests
        run: npm test
