# 
name: Develop Pull Requests Workflow
on: 
  pull_request:
    branches: develop

# Run Tests
jobs:
  build-and-test:
    # Run lastest ubuntu-latest OS
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js 16.2.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.2.0
          cache: 'npm'
      - name: Install Packages
        run: npm install
      
      - name: Set Enviroment
        env:
          PORT: 8080
          BCRYPT_COST: ${{secrets.BCRYPT_COST}}
          DB_HOST: ${{secrets.DEV_DB_HOST}}
          DB_PORT: ${{secrets.DEV_DB_PORT}}
          DB_NAME: ${{secrets.DEV_DB_NAME}}
          TOKEN_EXPIRES_NUMBER: ${{secrets.TOKEN_EXPIRES_NUMBER}}
          TOKEN_EXPIRES_UNIT: ${{secrets.TOKEN_EXPIRES_UNIT}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          TOKEN_EXPIRATION_DAYS: ${{secrets.TOKEN_EXPIRATION_DAYS}}
        run: echo env ${{secrets.DEV_DB_HOST}} ${{secrets.DEV_DB_PORT}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Run Tests
        run: npm test
